### ISSUE TITLE
In tab menu missed new containers created with Containers On The Go addon

### ISSUE THREAD

**Issue by MurzNN** [totallymike/contextPlus#30] opened 2017-11-21 10:29 UTC
I use [Containers On The Go addon](https://addons.mozilla.org/ro/firefox/addon/containers-on-the-go/) firefox addon - it quickly creates new containers, that available via all other Firefox interface immediately after creating. But they missed in contextPlus tab menu.

Seems contextPlus don't listen event when ContainersOnTheGo create new container, so don't update list of available containers.

Can you review and fix this? Thanks!

**Comment by gabrielfin** [comment] 2017-11-22 18:09
Duplicate of #27

**Closed** 2017-11-28 19:16 UTC
Labels: duplicate
